-- VHDL netlist generated by SCUBA Diamond (64-bit) 3.2.0.134
-- Module  Version: 3.5
--C:\Lattice\diamond\3.2_x64\ispfpga\bin\nt64\scuba.exe -w -n DLLl_in200M_out200M -lang vhdl -synth synplify -bus_exp 7 -bb -arch ep5c00 -type dll -dll_type cid -fin 200 -clkos_div 1 -fb_mode 0 

-- Wed Jan 28 16:09:06 2015

library IEEE;
use IEEE.std_logic_1164.all;
-- synopsys translate_off
library ecp3;
use ecp3.components.all;
-- synopsys translate_on

entity DLLl_in200M_out200M is
    port (
        clki: in  std_logic; 
        clkop: out  std_logic; 
        clkos: out  std_logic; 
        lock: out  std_logic; 
        aluhold: in  std_logic);
 attribute dont_touch : boolean;
 attribute dont_touch of DLLl_in200M_out200M : entity is true;
end DLLl_in200M_out200M;

architecture Structure of DLLl_in200M_out200M is

    -- internal signal declarations
    signal scuba_vlo: std_logic;
    signal scuba_vhi: std_logic;
    signal t_clkos: std_logic;
    signal t_clkop: std_logic;
    signal t_grayi0: std_logic;
    signal t_grayi1: std_logic;
    signal t_grayi2: std_logic;
    signal t_grayi3: std_logic;
    signal t_grayi4: std_logic;
    signal t_grayi5: std_logic;
    signal inci: std_logic;
    signal rstn: std_logic;
    signal t_clkfb: std_logic;

    -- local component declarations
    component VHI
        port (Z: out  std_logic);
    end component;
    component VLO
        port (Z: out  std_logic);
    end component;
    component CIDDLLB
        generic (LOCK_DELAY : in Integer; ALU_INIT_CNTVAL : in Integer; 
                GLITCH_TOLERANCE : in Integer; 
                ALU_UNLOCK_CNT : in Integer; ALU_LOCK_CNT : in Integer; 
                GSR : in String; CLKOS_DIV : in Integer; 
                CLKI_DIV : in Integer; CLKOS_FPHASE : in Integer; 
                CLKOS_PHASE : in Integer; CLKOP_PHASE : in Integer);
        port (CLKI: in  std_logic; CLKFB: in  std_logic; 
            RSTN: in  std_logic; ALUHOLD: in  std_logic; 
            INCI: in  std_logic; GRAYI5: in  std_logic; 
            GRAYI4: in  std_logic; GRAYI3: in  std_logic; 
            GRAYI2: in  std_logic; GRAYI1: in  std_logic; 
            GRAYI0: in  std_logic; CLKOP: out  std_logic; 
            CLKOS: out  std_logic; LOCK: out  std_logic);
    end component;
    attribute DEL4_GRAY : string; 
    attribute DEL3_GRAY : string; 
    attribute DEL2_GRAY : string; 
    attribute DEL1_GRAY : string; 
    attribute DEL0_GRAY : string; 
    attribute CLKOS_DUTY50 : string; 
    attribute CLKOP_DUTY50 : string; 
    attribute FREQUENCY_PIN_CLKOS : string; 
    attribute FREQUENCY_PIN_CLKOP : string; 
    attribute FREQUENCY_PIN_CLKI : string; 
    attribute DEL4_GRAY of Inst1_CIDDLLB : label is "DISABLED";
    attribute DEL3_GRAY of Inst1_CIDDLLB : label is "DISABLED";
    attribute DEL2_GRAY of Inst1_CIDDLLB : label is "DISABLED";
    attribute DEL1_GRAY of Inst1_CIDDLLB : label is "DISABLED";
    attribute DEL0_GRAY of Inst1_CIDDLLB : label is "DISABLED";
    attribute CLKOS_DUTY50 of Inst1_CIDDLLB : label is "DISABLED";
    attribute CLKOP_DUTY50 of Inst1_CIDDLLB : label is "DISABLED";
    attribute FREQUENCY_PIN_CLKOS of Inst1_CIDDLLB : label is "200.000000";
    attribute FREQUENCY_PIN_CLKOP of Inst1_CIDDLLB : label is "200";
    attribute FREQUENCY_PIN_CLKI of Inst1_CIDDLLB : label is "200";
    attribute syn_keep : boolean;
    attribute syn_noprune : boolean;
    attribute syn_noprune of Structure : architecture is true;
    attribute NGD_DRC_MASK : integer;
    attribute NGD_DRC_MASK of Structure : architecture is 1;

begin
    -- component instantiation statements
    scuba_vlo_inst: VLO
        port map (Z=>scuba_vlo);

    scuba_vhi_inst: VHI
        port map (Z=>scuba_vhi);

    Inst1_CIDDLLB: CIDDLLB
        generic map (LOCK_DELAY=>  100, GLITCH_TOLERANCE=>  2, 
        ALU_INIT_CNTVAL=>  10, ALU_UNLOCK_CNT=>  15, ALU_LOCK_CNT=>  3, 
        CLKI_DIV=>  1, CLKOS_DIV=>  1, CLKOS_FPHASE=>  0, CLKOS_PHASE=>  360, 
        CLKOP_PHASE=>  360, GSR=> "DISABLED")
        port map (CLKI=>clki, CLKFB=>t_clkfb, RSTN=>rstn, 
            ALUHOLD=>aluhold, INCI=>inci, GRAYI5=>t_grayi5, 
            GRAYI4=>t_grayi4, GRAYI3=>t_grayi3, GRAYI2=>t_grayi2, 
            GRAYI1=>t_grayi1, GRAYI0=>t_grayi0, CLKOP=>t_clkop, 
            CLKOS=>t_clkos, LOCK=>lock);

    t_clkfb <= t_clkop;
    clkos <= t_clkos;
    clkop <= t_clkop;
    t_grayi5 <= scuba_vlo;
    t_grayi4 <= scuba_vlo;
    t_grayi3 <= scuba_vlo;
    t_grayi2 <= scuba_vlo;
    t_grayi1 <= scuba_vlo;
    t_grayi0 <= scuba_vlo;
    inci <= scuba_vlo;
    rstn <= scuba_vhi;
end Structure;

-- synopsys translate_off
library ecp3;
configuration Structure_CON of DLLl_in200M_out200M is
    for Structure
        for all:VHI use entity ecp3.VHI(V); end for;
        for all:VLO use entity ecp3.VLO(V); end for;
        for all:CIDDLLB use entity ecp3.CIDDLLB(V); end for;
    end for;
end Structure_CON;

-- synopsys translate_on
